---
abstract: 'TAP as document data structure.'
author:
  - 'Steffen Schwigon <schwigon@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-DOM
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dumper: 0
  Sub::Exporter: 0
  Test::Harness: 3
  YAML::Syck: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
